In [3]:
import numpy as np

## 1

In [4]:
arr = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])

def prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1): 
        if n % i == 0:
            return False
    return True

def containsPrimes(array):
    mask = np.apply_along_axis(lambda row: np.any(np.vectorize(prime)(row)), axis=1, arr=array)
    return array[mask] 

print(containsPrimes(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


## 2

2.1

In [6]:
def checkerboard():
    return np.zeros((8, 8), dtype=int)

print(checkerboard())


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


2.2

In [9]:
def checkerboard():
    matrix= np.zeros((8, 8), dtype=int)
    matrix[0::2, 0::2] = 1
    return matrix

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


2.3

In [11]:
def checkerboard():
    matrix= np.zeros((8, 8), dtype=int)
    matrix[0::2, 0::2] = 1
    matrix[1::2, 1::2] = 1
    return matrix

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


2.4

In [12]:
def reverse_checkerboard():
    matrix= np.zeros((8, 8), dtype=int)
    matrix[0::2, 1::2] = 1
    matrix[1::2, 0::2] = 1
    return matrix

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 3

In [16]:
universe = np.array(['galaxy', 'clusters'])
def expansion(universe, n):
    spaces = ' ' * n
    return np.array([spaces.join(word) for word in universe])

print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


## 4

In [20]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
def secondDimmest(stars):
    sorted = np.sort(stars, axis=0)
    return sorted[1,:]

print(stars)
print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[ 611 1108 1732 1346  724]
